theme: jekyll-theme-cayman
title: gxc-team-12
description: This prototype is for a "one-stop-shop" website for the implementation and inspiration of a green wall, specifically in the city of Munich
logo: /pictures/Website_logo.png
show_downloads: "true"
